#!/usr/bin/env bash

cargo build --release

trap 'kill 0' EXIT

./target/release/latent server --tcp 0.0.0.0:8080 &

function run_test() {
    local delay=$1
    local driver=$2
    local c=$3
    local s=$4
    local m=$5

    printf '%s\t%s\t%s\t%s\t%s\t' "$delay" "$driver" "$c" "$s" "$m"

    local args="--connections $c --size $s"

    if [ "$m" == "TRUE" ]; then
        args+=" --multiplex"
    fi

    local port="4433"
    if [ "$driver" == "tcp" ]; then
        port="8080"
    fi

    ./target/release/latent $driver 127.0.0.1:$port $args --tsv --time 30
}

function delay() {
    sudo tc qdisc change dev lo root netem delay $1 || \
      sudo tc qdisc add dev lo root netem delay $1
}

function batch() {
    local c=$1
    for d in 0ms 1ms 10ms 50ms 100ms
    do
        delay $d
        for s in 1000 10000 100000 1000000 10000000
        do
            #run_test $d quic $c $s FALSE
            #run_test $d quic $c $s TRUE
            run_test $d tcp $c $s FALSE
            #run_test $d tls $c $s FALSE
        done
    done
}

printf "delay\tdriver\tconnections\tsize\tmultiplex\tmean\tstdev\tmin\tmax\tcount\ttime\ttps\n"

batch 1
#batch 2
#batch 5
#batch 10
